### ISSUE TITLE
Logger polution

### ISSUE THREAD

**Issue by ls-adrian** [quipo/statsd#12]
When `statsdbuffer.Close()` is called, it dumps `[BufferedStatsdClient] 2015/03/06 14:38:03 Asked to terminate. Flushing stats before returning.` out.

How do I prevent it from doing this?

**Comment by quipo** [comment]
you can now set sb.Verbose = false  in the buffered client instance   (see 1c66a23d163c4d9aee3728263e8ec19fafbff336)
