### ISSUE TITLE
GaugeDelta event Stats() should not send an absolute value of 0.

### ISSUE THREAD

**Issue by mmb** [quipo/statsd#23]
It appears to be copied from the Gauge event, which does not look like the correct logic for GaugeDelta.

**Comment by quipo** [comment]
hey Matthew, should I simply delete this line?   https://github.com/quipo/statsd/blob/master/event/gaugedelta.go#L34

**Comment by mmb** [comment]
Yes I think that's the correct fix.

If the delta value is negative, it can be sent as is.

If the delta value is positive it needs to have the '+' added or it will set the value of the gauge instead of applying a delta.
