### ISSUE TITLE
Package broken: *"github.com/quipo/statsd".StatsdBuffer does not implement "github.com/quipo/statsd".Statsd (missing CreateTCPSocket method)

### ISSUE THREAD

**Issue by oryband** [quipo/statsd#33]
Using `StatsdBuffer` now breaks my app. Trying to compile:
```go
*"github.com/quipo/statsd".StatsdBuffer does not implement "github.com/quipo/statsd".Statsd (missing CreateTCPSocket method)
```

**Comment by bolshoy** [comment]
+1

**Comment by oryband** [comment]
@quipo you should probably add more tests for all `Statsd` interface implementers

**Comment by quipo** [comment]
@oryband: sorry, I committed some things too soon.  Should be fixed now, I also added a simple test for the buffered client.
