### ISSUE TITLE
Concurrency usage of client returned by NewStatsdBuffer

### ISSUE THREAD

**Issue by vishal24tuniki** [quipo/statsd#42]
@quipo Can StatsdBuffer be used concurrently. Like in a production scenario if we create one instance of StatsdBuffer and use it across the code till the program exists, is it fine?

**Comment by Igorshp** [comment]
I'm also curious about this. 

Moving from default to buffered client introduced data races for us. @quipo any advice on the usage of the buffered client?

**Comment by quipo** [comment]
I always instantiate a new buffered client from within each goroutine. Unfortunately the collector isn't thread safe.
